spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: getir
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-service-group
      auto-offset-reset: earliest
    topics:
      customer-tier-update: customer-tier-update

mapstruct:
  verbose: true

logging:
  level:
    org.apache.kafka: ERROR
    kafka: ERROR
    org.springframework.kafka: ERROR

