spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer_db
    username: postgres
    password: getir
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
  sql:
    init:
      mode: always

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: customer-service-group
      auto-offset-reset: earliest
      enable-auto-commit: true
      properties:
        spring.json.trusted.packages: "*"
    producer:
      retries: 3
      batch-size: 16384
      buffer-memory: 33554432
      properties:
        spring.json.trusted.packages: "*"
    listener:
      type: batch
      ack-mode: batch
      poll-timeout: 3000
    topics:
      customer-tier-update: customer.events

mapstruct:
  verbose: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000   # 5 saniye bağlantı süresi
        readTimeout: 5000      # 5 saniye yanıt bekleme süresi
        loggerLevel: none      # Feign log seviyesini kapat

server:
  port: 8080

logging:
  level:
    root: INFO
    org.apache.kafka: OFF
    kafka: OFF
    org.springframework.kafka: OFF
    org.apache.kafka.clients.consumer: OFF
    org.apache.kafka.clients.producer: OFF
    org.apache.kafka.clients.admin: OFF
    org.apache.kafka.clients: OFF
    org.springframework.boot.autoconfigure.kafka: OFF
